// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pms-designs/BoldModern.tsx": () => import("../components/mockups/pms-designs/BoldModern.tsx"),
  "./components/mockups/pms-designs/CleanMinimal.tsx": () => import("../components/mockups/pms-designs/CleanMinimal.tsx"),
  "./components/mockups/pms-designs/WarmCommunity.tsx": () => import("../components/mockups/pms-designs/WarmCommunity.tsx")
};
